package datadog.trace.api;

import java.util.Map;
import java.util.concurrent.Callable;

/**
 * Public API for adding custom key-value pairs to SQL comments generated by the Datadog Java
 * tracer. This API allows external users to inject custom metadata into SQL comment traces.
 *
 * <p>This API only works when the dd-trace-java agent is loaded. If the agent is not present, these
 * methods will have no effect. Applications should handle the optional dependency by checking for
 * class availability before calling these methods.
 *
 * <p>Usage example:
 *
 * <pre>
 * // Add a custom field for a single operation
 * SQLCommenter.withCustomFields("tenant_id", "abc123", "request_id", "xyz789", () -> {
 *   // Execute database operations here
 *   return myRepository.findUser(userId);
 * });
 *
 * // Add custom fields using a map
 * Map<String, Object> customFields = Map.of(
 *   "tenant_id", "abc123",
 *   "operation", "user_lookup"
 * );
 * SQLCommenter.withCustomFields(customFields, () -> {
 *   return myRepository.findUser(userId);
 * });
 *
 * // Add a field for the current thread
 * SQLCommenter.put("correlation_id", requestId);
 * // All subsequent SQL operations will include this field
 * SQLCommenter.clear(); // Clear when done
 * </pre>
 */
public class SQLCommenter {

  /**
   * Adds a custom field to the current thread's SQL comment context.
   *
   * @param key the field key
   * @param value the field value (will be converted to string)
   * @throws IllegalArgumentException if key is null
   */
  public static void put(String key, Object value) {
    getContext().put(key, value);
  }

  /**
   * Gets a custom field from the current thread's SQL comment context.
   *
   * @param key the field key
   * @return the field value, or null if not found
   */
  public static String get(String key) {
    return getContext().get(key);
  }

  /**
   * Removes a custom field from the current thread's SQL comment context.
   *
   * @param key the field key
   * @return the previous value, or null if not found
   */
  public static String remove(String key) {
    return getContext().remove(key);
  }

  /** Clears all custom fields from the current thread's SQL comment context. */
  public static void clear() {
    getContext().clear();
  }

  /**
   * Returns true if the current thread has no custom SQL comment fields.
   *
   * @return true if no custom fields are set
   */
  public static boolean isEmpty() {
    return getContext().isEmpty();
  }

  /**
   * Gets a copy of the current thread's SQL comment context map.
   *
   * @return a copy of the current context map, or null if empty
   */
  public static Map<String, String> getCopyOfContextMap() {
    return getContext().getCopyOfContextMap();
  }

  /**
   * Executes a block of code with the given custom fields, restoring the original context
   * afterward.
   *
   * @param customFields the custom fields to use during execution
   * @param callable the code block to execute
   * @param <T> the return type of the callable
   * @return the result of executing the callable
   * @throws Exception if the callable throws an exception
   */
  public static <T> T withCustomFields(Map<String, Object> customFields, Callable<T> callable)
      throws Exception {
    return getContext().withSQLCommentFields(customFields, callable::call);
  }

  /**
   * Executes a block of code with the given custom fields, restoring the original context
   * afterward.
   *
   * @param callable the code block to execute
   * @param keyValuePairs alternating key-value pairs to add to the context
   * @param <T> the return type of the callable
   * @return the result of executing the callable
   * @throws Exception if the callable throws an exception
   */
  public static <T> T withCustomFields(Callable<T> callable, Object... keyValuePairs)
      throws Exception {
    return getContext().withSQLCommentFields(callable::call, keyValuePairs);
  }

  /**
   * Executes a runnable with the given custom fields, restoring the original context afterward.
   *
   * @param customFields the custom fields to use during execution
   * @param runnable the code block to execute
   */
  public static void withCustomFields(Map<String, Object> customFields, Runnable runnable) {
    try {
      withCustomFields(
          customFields,
          () -> {
            runnable.run();
            return null;
          });
    } catch (Exception e) {
      if (e instanceof RuntimeException) {
        throw (RuntimeException) e;
      }
      throw new RuntimeException(e);
    }
  }

  /**
   * Executes a runnable with the given custom fields, restoring the original context afterward.
   *
   * @param runnable the code block to execute
   * @param keyValuePairs alternating key-value pairs to add to the context
   */
  public static void withCustomFields(Runnable runnable, Object... keyValuePairs) {
    try {
      withCustomFields(
          () -> {
            runnable.run();
            return null;
          },
          keyValuePairs);
    } catch (Exception e) {
      if (e instanceof RuntimeException) {
        throw (RuntimeException) e;
      }
      throw new RuntimeException(e);
    }
  }

  // Direct access to the context - simpler than the provider pattern
  private static SQLCommenterContextAccess getContext() {
    return SQLCommenterContextHolder.INSTANCE;
  }

  private static class SQLCommenterContextHolder {
    private static final SQLCommenterContextAccess INSTANCE = createInstance();

    private static SQLCommenterContextAccess createInstance() {
      try {
        Class<?> contextClass =
            Class.forName("datadog.trace.instrumentation.jdbc.SQLCommenterContext");
        return new DirectSQLCommenterContextAccess(contextClass);
      } catch (ClassNotFoundException | LinkageError e) {
        // This should not happen if the dd-trace-java agent is properly loaded
        throw new RuntimeException(
            "SQLCommenterContext is not available. Ensure dd-trace-java agent is loaded.", e);
      }
    }
  }

  // Direct access interface - much simpler than the provider pattern
  private interface SQLCommenterContextAccess {
    void put(String key, Object value);

    String get(String key);

    String remove(String key);

    void clear();

    boolean isEmpty();

    Map<String, String> getCopyOfContextMap();

    <T> T withSQLCommentFields(Map<String, Object> contextMap, SQLCommenterBlock<T> block);

    <T> T withSQLCommentFields(SQLCommenterBlock<T> block, Object... keyValuePairs);
  }

  @FunctionalInterface
  private interface SQLCommenterBlock<T> {
    T execute() throws Exception;
  }

  private static class DirectSQLCommenterContextAccess implements SQLCommenterContextAccess {
    private final Class<?> contextClass;

    public DirectSQLCommenterContextAccess(Class<?> contextClass) {
      this.contextClass = contextClass;
    }

    @Override
    public void put(String key, Object value) {
      try {
        contextClass.getMethod("put", String.class, Object.class).invoke(null, key, value);
      } catch (Exception e) {
        throw new RuntimeException("Failed to put SQL comment field", e);
      }
    }

    @Override
    public String get(String key) {
      try {
        return (String) contextClass.getMethod("get", String.class).invoke(null, key);
      } catch (Exception e) {
        throw new RuntimeException("Failed to get SQL comment field", e);
      }
    }

    @Override
    public String remove(String key) {
      try {
        return (String) contextClass.getMethod("remove", String.class).invoke(null, key);
      } catch (Exception e) {
        throw new RuntimeException("Failed to remove SQL comment field", e);
      }
    }

    @Override
    public void clear() {
      try {
        contextClass.getMethod("clear").invoke(null);
      } catch (Exception e) {
        throw new RuntimeException("Failed to clear SQL comment context", e);
      }
    }

    @Override
    public boolean isEmpty() {
      try {
        return (Boolean) contextClass.getMethod("isEmpty").invoke(null);
      } catch (Exception e) {
        throw new RuntimeException("Failed to check if SQL comment context is empty", e);
      }
    }

    @Override
    @SuppressWarnings("unchecked")
    public Map<String, String> getCopyOfContextMap() {
      try {
        return (Map<String, String>) contextClass.getMethod("getCopyOfContextMap").invoke(null);
      } catch (Exception e) {
        throw new RuntimeException("Failed to get copy of SQL comment context map", e);
      }
    }

    @Override
    @SuppressWarnings("unchecked")
    public <T> T withSQLCommentFields(Map<String, Object> contextMap, SQLCommenterBlock<T> block) {
      try {
        Class<?> blockClass =
            Class.forName(
                "datadog.trace.instrumentation.jdbc.SQLCommenterContext$SQLCommenterBlock");
        Object blockProxy =
            java.lang.reflect.Proxy.newProxyInstance(
                blockClass.getClassLoader(),
                new Class<?>[] {blockClass},
                (proxy, method, args) -> block.execute());
        return (T)
            contextClass
                .getMethod("withSQLCommentFields", Map.class, blockClass)
                .invoke(null, contextMap, blockProxy);
      } catch (Exception e) {
        throw new RuntimeException("Failed to execute with SQL comment fields", e);
      }
    }

    @Override
    @SuppressWarnings("unchecked")
    public <T> T withSQLCommentFields(SQLCommenterBlock<T> block, Object... keyValuePairs) {
      try {
        Class<?> blockClass =
            Class.forName(
                "datadog.trace.instrumentation.jdbc.SQLCommenterContext$SQLCommenterBlock");
        Object blockProxy =
            java.lang.reflect.Proxy.newProxyInstance(
                blockClass.getClassLoader(),
                new Class<?>[] {blockClass},
                (proxy, method, args) -> block.execute());
        return (T)
            contextClass
                .getMethod("withSQLCommentFields", blockClass, Object[].class)
                .invoke(null, blockProxy, keyValuePairs);
      } catch (Exception e) {
        throw new RuntimeException("Failed to execute with SQL comment fields", e);
      }
    }
  }
}
